name: streamlit
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - spacy
  - gensim
  - category_encoders
  - nltk
  - matplotlib
  - pip
  - pip:
    - streamlit
    - distance